version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=todo
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - todo_pg_data:/bitnami/postgresql
volumes:
  todo_pg_data: